import {useEffect, useState} from 'react';
import type {AnalysisKind, Json} from './types';
import {JsonEditor} from './Editors';
import {isPrescribedPower} from './types';

type Values=Record<string,Json>;
const object=(value:Json|undefined):Values=>value&&typeof value==='object'&&!Array.isArray(value)?value:{};
function Numeric({label,value,onChange,unit,scale=1,fallback,min,max}:{label:string;value:Json|undefined;onChange:(value:number)=>void;unit?:string;scale?:number;fallback?:number;min?:number;max?:number}){
  const current=typeof value==='number'?value:fallback;
  const normalized=current===undefined?'':String(Number((current/scale).toPrecision(10)));
  const [text,setText]=useState(normalized);
  useEffect(()=>setText(normalized),[normalized]);
  return <label>{label}<div className="input-unit"><input aria-label={label} type="number" step="any" min={min} max={max} value={text} onChange={e=>{setText(e.target.value);if(e.target.value.trim()&&Number.isFinite(Number(e.target.value)))onChange(Number(e.target.value)*scale);}} onBlur={()=>{if(!text.trim())setText(normalized);}}/>{unit&&<span>{unit}</span>}</div></label>;
}
export function ExternalCircuitSketch({enabled}:{enabled:boolean}){return <div className="external-sketch"><svg viewBox="0 0 300 95" role="img" aria-label={enabled?'電源、直列R・L、DCブロックC、プラズマ、並列Cの外部回路':'理想RF電極駆動'} fill="none" stroke="currentColor" strokeWidth="1.7"><circle cx="22" cy="46" r="14"/><path d="M8 46q7-14 14 0t14 0M22 60v22h255V30"/>{enabled?<><path d="M22 32V20h33l4-7 8 14 8-14 8 14 4-7h13c0-16 11-16 11 0c0-16 11-16 11 0h13M139 11v18m8-18v18m0-9h80M192 20v30m-8 0h16m-16 7h16m-8 0v25"/><text x="57" y="48">R</text><text x="105" y="48">L</text><text x="130" y="48">Cblock</text><text x="183" y="72">Cshunt</text></>:<path d="M22 32V20h205"/>}<rect x="227" y="8" width="50" height="35" rx="6"/><text x="252" y="30" textAnchor="middle">PLASMA</text><text x="11" y="94">source</text><text x="237" y="61">electrode</text></svg><p className="muted text-small">{enabled?'電圧は電源側ピーク値。電極側波形・吸収電力を計算します。':'電圧は電極側ピーク値。外部回路を有効にすると電源側の値になります。'}</p></div>;}
function TransportImport({onImport}:{onImport:(value:Values)=>void}){const [error,setError]=useState('');return <><label className="file-upload">出典付き輸送データJSON<input type="file" accept=".json,application/json" onChange={e=>{const file=e.target.files?.[0];if(file)void file.text().then(text=>{const data=JSON.parse(text);if(!data||typeof data!=='object'||Array.isArray(data))throw new Error('electron_transportオブジェクトを指定してください。');onImport(data);setError('');}).catch(err=>setError(err.message));e.target.value='';}}/></label>{error&&<p className="field-error">{error}</p>}</>;}
function SurfaceControls({values,set}:{values:Values;set:(key:string,v:Json)=>void}){
  const configured=object(values.surface_parameters);
  const [draft,setDraft]=useState<Record<string,Record<string,string>>>({});
  const [error,setError]=useState('');
  useEffect(()=>{const next:Record<string,Record<string,string>>={};for(const role of ['cathode','anode','wall']){const s=object(configured[role]);next[role]={material:String(s.material??''),state:String(s.state??''),temperature_k:String(s.temperature_k??300),gamma_o:String(s.gamma_o??''),gamma_metastable:typeof s.gamma_metastable==='object'?'':String(s.gamma_metastable??''),secondary_electron_yield:String(s.secondary_electron_yield??''),source:typeof s.provenance==='string'?s.provenance:JSON.stringify(s.provenance??'').replace(/^"|"$/g,'')};}setDraft(next);},[JSON.stringify(configured)]);
  function edit(role:string,key:string,v:string){setDraft(previous=>({...previous,[role]:{...previous[role],[key]:v}}));}
  function apply(){const next:Values={};for(const role of ['cathode','anode','wall']){const s=draft[role];if(!s?.material.trim()||!s.source.trim()||['temperature_k','gamma_o','gamma_metastable','secondary_electron_yield'].some(k=>!s[k]?.trim()||!Number.isFinite(Number(s[k])))){setError('3面すべての材料・係数・出典または仮定を入力してください。材料名から係数は推定しません。');return;}if(Number(s.temperature_k)<=0||['gamma_o','gamma_metastable','secondary_electron_yield'].some(k=>Number(s[k])<0||Number(s[k])>1)){setError('表面温度は正の値、確率・収率は0〜1で指定してください。');return;}next[role]={material:s.material,state:s.state,temperature_k:Number(s.temperature_k),gamma_o:Number(s.gamma_o),gamma_metastable:Number(s.gamma_metastable),secondary_electron_yield:Number(s.secondary_electron_yield),provenance:{gamma_o:s.source,gamma_metastable:s.source,secondary_electron_yield:s.source}};}set('surface_parameters',next);setError('');}
  return <details className="advanced"><summary>表面・材料条件</summary><p className="muted text-small">Siなどの材料名から反応確率は決まりません。出典または明示した仮定を3面ごとに指定します。未設定時はモデルの既存条件を使用します。</p>{['cathode','anode','wall'].map(role=><details className="sub-options" key={role}><summary>{({cathode:'駆動電極',anode:'接地電極',wall:'チャンバー壁'} as Record<string,string>)[role]}</summary>{[{key:'material',name:'材料名（例：Si）'},{key:'state',name:'表面状態'},{key:'temperature_k',name:'表面温度（K）'},{key:'gamma_o',name:'O再結合確率 γO'},{key:'gamma_metastable',name:'準安定失活確率'},{key:'secondary_electron_yield',name:'二次電子収率'},{key:'source',name:'係数の出典・仮定'}].map(f=><label key={f.key}>{f.name}<input value={draft[role]?.[f.key]??''} onChange={e=>edit(role,f.key,e.target.value)}/></label>)}</details>)}{error&&<p className="field-error">{error}</p>}<div className="flex-row"><button className="button small secondary" onClick={apply}>表面条件を適用</button>{Object.keys(configured).length>0&&<button className="text-button" onClick={()=>set('surface_parameters',{})}>設定を解除</button>}</div><JsonEditor label="表面条件・個別出典・不確かさ範囲" value={configured} rows={6} onApply={v=>{if(!v||Array.isArray(v)||typeof v!=='object')throw new Error('JSONオブジェクトを指定してください。');set('surface_parameters',v as Json);}}/></details>;
}
export function PlasmaControls({kind,values,set,componentMode=false}:{kind:AnalysisKind;values:Values;set:(key:string,v:Json)=>void;componentMode?:boolean}){
  const circuit=object(values.external_circuit),transport=object(values.electron_transport),heating=object(values.electron_heating),iedf=object(values.iedf),validation=object(values.numerical_validation);
  const nested=(key:string,part:Values,name:string,value:Json)=>set(key,{...part,[name]:value});
  const global=kind==='global'||kind==='global_transient';
  const prescribed=isPrescribedPower({kind,settings:values});
  const rf=kind!=='radial'&&!prescribed;
  const canPrescribe=kind==='global_transient'||kind==='global'&&values.gas==='O2';
  return <div className="plasma-controls">
    {global&&canPrescribe&&<label>電力の与え方<select aria-label="電力の与え方" value={prescribed?'prescribed_absorbed':'rf_coupled'} onChange={e=>{set('power_mode',e.target.value);}}><option value="rf_coupled">RF回路と結合</option><option value="prescribed_absorbed">総吸収プラズマ電力を指定</option></select></label>}
    {global&&prescribed&&<><Numeric label="総吸収プラズマ電力" value={values.absorbed_power_w} fallback={500} unit="W" min={0} onChange={v=>set('absorbed_power_w',v)}/><p className="muted text-small">電子・イオンの吸収を含む総電力。RF波形は指定電力0D計算では生成しません。</p></>}
    {!componentMode&&rf&&<details className="advanced"><summary>外部回路・RF駆動</summary><label className="check-label"><input type="checkbox" checked={Object.keys(circuit).length>0} onChange={e=>set('external_circuit',e.target.checked?{source_resistance_ohm:50,series_inductance_h:0,shunt_capacitance_f:0,dc_block_capacitance_f:1e-6,dc_voltage_v:0,voltage_definition:'source'}:{})}/>電源側の外部回路を有効化</label><ExternalCircuitSketch enabled={Object.keys(circuit).length>0}/>{Object.keys(circuit).length>0&&<div className="form-grid">{[{key:'source_resistance_ohm',name:'電源抵抗',unit:'Ω',fallback:50},{key:'series_inductance_h',name:'直列インダクタ',unit:'µH',scale:1e-6,fallback:0},{key:'shunt_capacitance_f',name:'並列容量',unit:'pF',scale:1e-12,fallback:0},{key:'dc_block_capacitance_f',name:'DCブロック容量',unit:'nF',scale:1e-9,fallback:1e-6},{key:'dc_voltage_v',name:'DC電源電圧',unit:'V',fallback:0}].map(f=><Numeric key={f.key} label={f.name} value={circuit[f.key]} unit={f.unit} scale={f.scale} fallback={f.fallback} onChange={v=>nested('external_circuit',circuit,f.key,v)}/>)}</div>}<h4>第2周波数・パルス</h4><p className="muted text-small">第2RF振幅0で単一周波数。パルス周波数を指定すると包絡を適用します。</p><div className="form-grid">{[{key:'second_frequency_hz',name:'第2 RF周波数',unit:'MHz',scale:1e6},{key:'second_rf_peak_voltage',name:'第2 RFピーク電圧',unit:'V',fallback:0},{key:'second_phase_deg',name:'第2 RF位相',unit:'°',fallback:0},{key:'pulse_frequency_hz',name:'パルス周波数',unit:'kHz',scale:1e3},{key:'pulse_duty_cycle',name:'パルスデューティ',fallback:0.5},{key:'pulse_off_fraction',name:kind==='global_transient'?'OFF時平均電力比':'OFF時RF振幅比',fallback:0}].map(f=><Numeric key={f.key} label={f.name} value={values[f.key]} unit={f.unit} scale={f.scale} fallback={f.fallback} onChange={v=>set(f.key,v)}/>)}</div></details>}
    {String(values.gas)==='O2'&&global&&<details className="advanced"><summary>O₂反応・中性ガス輸送</summary><p className="muted text-small">文献反応ネットワークを使用します。壁の反応係数は材料条件と出典を確認してください。</p><label>壁端密度比モデル<select aria-label="壁端密度比モデル" value={String(values.transport_mode??'explicit_h')} onChange={e=>{set('transport_mode',e.target.value);}}><option value="explicit_h">hを明示指定</option><option value="gudmundsson_2000">Gudmundsson (2000) の輸送閉包</option></select></label><div className="form-grid">{[{key:'flow_sccm',name:'流量',unit:'sccm',fallback:50},{key:'diffusion_o_m2_s',name:'O拡散係数',unit:'m²/s',fallback:1.2},{key:'diffusion_o2_m2_s',name:'O₂拡散係数',unit:'m²/s',fallback:0.84},...(values.transport_mode==='gudmundsson_2000'?[]:[{key:'axial_edge_factor',name:'軸方向h',fallback:0.5},{key:'radial_edge_factor',name:'径方向h',fallback:0.5}])].map(f=><Numeric key={f.key} label={f.name} value={values[f.key]} unit={f.unit} fallback={f.fallback} onChange={v=>set(f.key,v)}/>)}</div><JsonEditor label="O / O₂ 電子運動量衝突周波数（s⁻¹）" value={values.electron_momentum_nu_s??{O:1e7,O2:1e7}} rows={3} onApply={v=>{if(!v||typeof v!=='object'||Array.isArray(v))throw new Error('OとO2の係数を指定してください。');set('electron_momentum_nu_s',v as Json);}}/></details>}
    <details className="advanced"><summary>{kind==='radial'?'運動量衝突周波数':'電子輸送・EEDF・加熱（実験的）'}</summary>{kind==='radial'?<Numeric label="運動量衝突周波数 ν" value={values.momentum_collision_frequency_hz} unit="s⁻¹" fallback={1e7} onChange={v=>set('momentum_collision_frequency_hz',v)}/>:<><label>運動量衝突周波数<select aria-label="運動量衝突周波数" value={String(transport.mode??'explicit_nu')} onChange={e=>set('electron_transport',{...transport,mode:e.target.value})}><option value="explicit_nu">νを明示指定</option><option value="cross_section_eedf">断面積とEEDFから積分</option></select></label>{transport.mode!=='cross_section_eedf'?<Numeric label="運動量衝突周波数 ν" value={values.momentum_collision_frequency_hz} unit="s⁻¹" fallback={1e7} onChange={v=>set('momentum_collision_frequency_hz',v)}/>:<><p className="warning-box">エネルギー格子・断面積・出典を入力してください。断面積の仮データは用意しません。Maxwellianまたは表形式EEDFを指定できます。</p><TransportImport onImport={data=>set('electron_transport',{...data,mode:'cross_section_eedf'})}/><JsonEditor label="electron_transport（出典付き断面積 / EEDF）" value={transport} rows={10} onApply={v=>{if(!v||typeof v!=='object'||Array.isArray(v))throw new Error('JSONオブジェクトを指定してください。');set('electron_transport',v as Json);}}/></>}</>}{rf&&<><label>電子加熱モデル<select aria-label="電子加熱モデル" value={String(heating.mode??'bulk_drude')} onChange={e=>set('electron_heating',{...heating,mode:e.target.value})}><option value="bulk_drude">バルクDrude加熱</option><option value="moving_wall_maxwellian">移動シース境界・Maxwellian</option></select></label>{heating.mode==='moving_wall_maxwellian'&&<><Numeric label="反射確率" value={heating.reflection_probability} fallback={1} min={0} max={1} onChange={v=>nested('electron_heating',heating,'reflection_probability',v)}/><p className="warning-box">縮約モデル。周期平均の不可逆シース加熱を等価抵抗へ戻し、RF電流との固定点を計算します。圧力仕事・加熱の収支残差とモデルの適用範囲を確認してください。</p></>}</>}{prescribed&&<p className="muted text-small">指定電力計算ではRFのDrude・移動シース加熱モデルを使用しません。</p>}</details>
    {kind!=='radial'&&<SurfaceControls values={values} set={set}/>}
    {rf&&['ccp','global'].includes(kind)&&<details className="advanced"><summary>イオンエネルギー分布（IEDF・実験的）</summary><label className="check-label"><input type="checkbox" checked={iedf.enabled===true} onChange={e=>nested('iedf',iedf,'enabled',e.target.checked)}/>シース内粒子軌道を計算</label><p className="muted text-small">計算されたシース波形で固定幅・一様電場の粒子軌道を追跡します。衝突断面積はユーザーが指定した一定値です。</p>{iedf.enabled===true&&<><div className="form-grid">{[{key:'particles_per_species',name:'粒子数 / イオン種',fallback:512,min:16,max:20000},{key:'histogram_bins',name:'エネルギービン数',fallback:80,min:8,max:512},{key:'steps_per_rf_period',name:'1周期の積分ステップ',fallback:256,min:16,max:8192},{key:'seed',name:'乱数シード',fallback:17},{key:'charge_exchange_cross_section_m2',name:'電荷交換断面積',unit:'m²',fallback:0},{key:'sheath_thickness_m',name:'明示シース幅（任意）',unit:'mm',scale:1e-3}].map(f=><Numeric key={f.key} label={f.name} value={iedf[f.key]} unit={f.unit} scale={f.scale} fallback={f.fallback} min={f.min} max={f.max} onChange={v=>nested('iedf',iedf,f.key,v)}/>)}</div><JsonEditor label="イオン種（未指定時はモデルのイオン）" value={iedf.species??[]} rows={5} onApply={v=>{if(!Array.isArray(v))throw new Error('イオン種の配列を指定してください。');nested('iedf',iedf,'species',v as Json);}}/></>}</details>}
    {kind==='radial'&&<details className="advanced" open><summary>径方向・分布回路</summary><p className="warning-box">同心円環の縮約回路です。密度は一様な指定値。径方向の反応拡散は解きません。</p><label>給電位置<select aria-label="給電位置" value={String(values.radial_feed??'center')} onChange={e=>set('radial_feed',e.target.value)}><option value="center">中心給電</option><option value="edge">外周給電</option></select></label><div className="form-grid">{[{key:'radial_cells',name:'径方向セル数',fallback:32,min:4,max:128},{key:'electrode_sheet_resistance_ohm',name:'電極シート抵抗',unit:'Ω',fallback:0.02},{key:'electrode_sheet_inductance_h',name:'電極シートL',unit:'nH',scale:1e-9,fallback:2e-9},{key:'ion_density_m3',name:'イオン密度',unit:'m⁻³',fallback:1e16},{key:'mean_cathode_sheath_voltage_v',name:'駆動側平均シース電圧',unit:'V',fallback:100},{key:'mean_anode_sheath_voltage_v',name:'接地側平均シース電圧',unit:'V',fallback:30}].map(f=><Numeric key={f.key} label={f.name} value={values[f.key]} unit={f.unit} scale={f.scale} fallback={f.fallback} min={f.min} max={f.max} onChange={v=>set(f.key,v)}/>)}</div></details>}
    {kind==='global_transient'&&<details className="advanced" open><summary>時間発展・ガス加熱</summary><p className="muted text-small">BDFで粒子・電子エネルギー・ガス温度を積分します。RF再評価間隔とマクロ時間を分離します。</p><div className="form-grid">{[{key:'stop_time_s',name:'終了時間',unit:'ms',scale:1e-3,fallback:0.001},{key:'output_points',name:'出力点数',fallback:201},...(!prescribed?[{key:'rf_update_interval_s',name:'RF再評価間隔',unit:'µs',scale:1e-6}]:[]),{key:'initial_electron_density_m3',name:'初期電子密度',unit:'m⁻³'},{key:'initial_electron_temperature_ev',name:'初期電子温度',unit:'eV'},{key:'initial_gas_temperature_k',name:'初期ガス温度',unit:'K'},{key:'background_gas_temperature_k',name:'背景ガス温度',unit:'K'},{key:'gas_wall_conductance_w_k',name:'壁への熱伝導',unit:'W/K',fallback:0},{key:'gas_heat_capacity_j_k',name:'ガス熱容量（任意）',unit:'J/K'},{key:'gas_inelastic_heating_fraction',name:'非弾性損失のガス加熱率',fallback:0},{key:'gas_ion_heating_fraction',name:'イオン損失のガス加熱率',fallback:0},...(prescribed?[{key:'pulse_frequency_hz',name:'電力パルス周波数',unit:'kHz',scale:1e3},{key:'pulse_duty_cycle',name:'デューティ',fallback:0.5},{key:'pulse_off_fraction',name:'OFF時の電力比',fallback:0}]:[])].map(f=><Numeric key={f.key} label={f.name} value={values[f.key]} unit={f.unit} scale={f.scale} fallback={f.fallback} onChange={v=>set(f.key,v)}/>)}</div></details>}
    <details className="advanced"><summary>数値収束・精細化検証</summary><div className="form-grid">{rf&&<><Numeric label="RF周期数" value={values.cycles} fallback={80} min={16} max={120} onChange={v=>set('cycles',v)}/><Numeric label="RF周期あたり点数" value={values.points_per_cycle} fallback={256} min={64} max={512} onChange={v=>set('points_per_cycle',v)}/></>}{kind==='global'&&!prescribed&&<Numeric label="グローバル反復上限" value={values.max_global_iterations} fallback={18} onChange={v=>set('max_global_iterations',v)}/>}</div>{kind==='global'&&prescribed?<p className="muted text-small">定常の指定電力計算にはRF刻みの精細化は適用しません。反応計算の収束・収支診断を結果で確認してください。</p>:<label className="check-label"><input type="checkbox" checked={validation.enabled===true} onChange={e=>set('numerical_validation',{...validation,enabled:e.target.checked,refine_points:true,refine_cycles:true,relative_tolerance:validation.relative_tolerance??0.02})}/>追加計算で数値精細化を検証</label>}{!(kind==='global'&&prescribed)&&validation.enabled===true&&<><Numeric label="相対許容差" value={validation.relative_tolerance} fallback={0.02} min={0.000000001} max={0.2} onChange={v=>nested('numerical_validation',validation,'relative_tolerance',v)}/><p className="muted text-small">RFは点数・周期数、径方向はセル数、時間発展はODE許容差を変更して比較します。実験値との比較は参照データで行います。</p></>}</details>
  </div>;
}
